name: 'Test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  # Build and test
  Build-and-Test:
    runs-on: ubuntu-latest
    container: ghcr.io/galacticusorg/buildenv:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate configure
        run: |
          cd $GITHUB_WORKSPACE
          apt update
          apt install -y bison flex
          git config --global --add safe.directory $GITHUB_WORKSPACE
          set -o pipefail
          autoreconf --install --force
          cd ..
          zip -r libmatheval.zip libmatheval --exclude "libmatheval/.github/*" --exclude "libmatheval/.git/*" --exclude "libmatheval/autom4te/*"
          mv libmatheval.zip libmatheval/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-archive
          path: 'libmatheval.zip'
      - name: Build and test
        run: |          
          LIBS="-lguile" LDFLAGS="-L/usr/local/lib" CFLAGS="-L/usr/local/lib -I/usr/local/include -I/usr/include/x86_64-linux-gnu" ./configure
          make -j2 2>&1 | tee build.log
          grep -v -q Error: build.log
          grep -v -q Warning: build.log
          make -j2 check 2>&1 | tee build.log
          grep -v -q Error: build.log
          grep -v -q Warning: build.log
          set +o pipefail
  Update-Release-Tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: Build-and-Test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: release-archive
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest libmatheval.zip
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update tag
        run: |
          git tag -f latest
          git push origin -f latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
